### ISSUE TITLE
NuGet package Id comes through with incorrect case

### ISSUE THREAD

**Issue by ianbattersby** [NancyFx/Nancy.Bootstrappers.StructureMap#11]
In packages.config;

    <package id="Nancy.Bootstrappers.StructureMap" version="0.20.0" targetFramework="net45" />

Project reference is lowercase as per nuspec id;

    <HintPath>..\packages\Nancy.Bootstrappers.StructureMap.0.20.0\lib\net40\Nancy.Bootstrappers.StructureMap.dll</HintPath>

BUT the physical directory is not;

![image](https://f.cloud.github.com/assets/185776/1218834/a6d16c86-26c0-11e3-8046-f698748e7000.png)

Which means the build fails on (case-sensitive) Mono.

To fix this you usually need to ask the wonderful @JeffHandley to do some voodoo on the nuget server (e.g. https://github.com/Particular/NServiceBus/issues/1271).

**Comment by khellang** [comment]
This has been sitting here for a while. Is this still a problem?
