### ISSUE TITLE
Something is wrong and I have no idea what!

### ISSUE THREAD

**Issue by EtharAlali** [NancyFx/Nancy.Bootstrappers.StructureMap#30]
This is an enhancement to docs. Having installed the latest NuGet packages for Nancy and StructureMapNancyBootstrapper, I've had a horrific day trying to get something basic working inside an existing project I could simply have used WebAPI for (specifically, being fairly new to Nancy and it's bootstrapper, I just want a tutorial showing a non-self-hosted setup using the StructureMap Bootstrapper, using an appropriate VS2013 template, for RESTful API endpoints - But I suspect such noobie issues are for SO not here, since nobody has blogged an end-to end with that specific scenario :) 

What I'd really like is an end-to-end walk through for non-happy path stuff, since small scale, super-duper-happy-path stuff trades-off against the pain of working with existing legacy code (which is often far from a happy experience and there is naturally so much more of it, so I could argue that's the real 'happy path'). Indeed, copying and pasting the sample from the README.md into VS and I get the attached image indicating that no ApplicationStartup etc. methods exist to override. Has the boot-strapper not got these methods any more? Or perhaps I'm using the wrong IContainer? 

So, after that rant, would it be too much to ask to include the using statements as part of the sample?

Thanks
![nancyproblem](https://cloud.githubusercontent.com/assets/2097628/7238582/3fb5cbf8-e79b-11e4-90de-d9040a31f319.PNG)

**Comment by khellang** [comment]
Well, something is clearly wrong.

> I've had a horrific day trying to get something basic working inside an existing project I could simply have used WebAPI for

Sorry Nancy made your day horrific. If you could do the same with WebAPI so easily, I suggest you do so instead.

> I just want a tutorial showing a non-self-hosted setup using the StructureMap Bootstrapper

If you want docs on hosting a non-self-hosted setup, I suggest you look at the wiki. There's lots of guidance on hosting with [ASP.NET](https://github.com/NancyFx/Nancy/wiki/Hosting-Nancy-with-asp.net), [WCF](https://github.com/NancyFx/Nancy/wiki/Hosting-Nancy-with-wcf), [Azure](https://github.com/NancyFx/Nancy/wiki/Hosting-nancy-with-azure), [OWIN](https://github.com/NancyFx/Nancy/wiki/Hosting-nancy-with-owin) (Katana), [Umbraco](https://github.com/NancyFx/Nancy/wiki/Hosting-Nancy-with-Umbraco), [Nginx on Ubuntu](https://github.com/NancyFx/Nancy/wiki/Hosting-Nancy-with-Nginx-on-Ubuntu) and with [FastCGI](https://github.com/NancyFx/Nancy/wiki/Hosting-Nancy-with-FastCgi). The bootstrapper little to do with the hosting you choose. You just install the bootstrapper of choice, derive from it and override the methods you need. There's loads of examples on custom bootstrappers under in the [demo projects](https://github.com/NancyFx/Nancy/tree/master/src) (Nancy.Demo.*). We would expect people using Nancy to know how to override methods properly.

> What I'd really like is an end-to-end walk through for non-happy path stuff

What specifically do you want here? It's impossible to provide a full guide on building complex applications with Nancy. People are doing large scale, production stuff with it. Not sure we can build your applications for you by providing much documentation on this.

> would it be too much to ask to include the using statements as part of the sample?

No. I've already added them. We also take PRs, you know?

Also, this works perfectly fine here:
![2015-04-21_10-38-44](https://cloud.githubusercontent.com/assets/582487/7248494/5ac1fd0e-e813-11e4-875f-32401ee035cb.png)

> I suspect such noobie issues are for SO not here

Exactly. If you have other problems trying to figure out the correct using statements etc. I suggest you take it to SO. That's not really Nancy specific.

Thanks!
